services:
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./docker/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 10s
      retries: 3

  mongo:
    image: mongo:latest
    restart: always
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - ./docker/mongodata:/data/db
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'mongosh --eval ''db.adminCommand("ping")'' --quiet || exit 1',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redisdata:/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 30
    command: ["redis-server"]

  minio:
    image: bitnami/minio:latest
    restart: always
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./docker/minio:/bitnami/minio/data
