services:
  back-innogram:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - APP=innogram
    ports:
      - "3000:3000"
    env_file:
      - .env
      - ./backend/.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - innogram

  back-auth:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - APP=auth
    ports:
      - "3001:3000"
    env_file:
      - .env
      - ./backend/.env
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - innogram

  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./docker/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - innogram

  mongo:
    image: mongo:latest
    restart: always
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - ./docker/mongodata:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 40s
    networks:
      - innogram

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redisdata:/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 30
    networks:
      - innogram
    command: ["redis-server"]

  minio:
    image: bitnami/minio:latest
    restart: always
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./docker/minio:/bitnami/minio/data
    networks:
      - innogram

networks:
  innogram:
    driver: bridge
